### ISSUE TITLE
Add image sprite URL to items

### ISSUE THREAD

**Issue by gc** [osrsbox/osrsbox-db#120]
I'd propose that image sprite URL's be added to item objects

Visiting https://services.runescape.com/m=itemdb_oldschool/api/catalogue/items.json?category=1&alpha=twisted%20buckler will show you two icon properties:

```json
{
  "icon": "https://secure.runescape.com/m=itemdb_oldschool/1561977037620_obj_sprite.gif?id=21000",
  "icon_large": "https://secure.runescape.com/m=itemdb_oldschool/1561977037620_obj_big.gif?id=21000",
  "id": 21000,
  "type": "Default",
  "typeIcon": "https://www.runescape.com/img/categories/Default",
  "name": "Twisted buckler",
  "description": "A buckler carved from the twisted remains of the Great Olm.",
  "current": {
    "trend": "neutral",
    "price": "5.9m"
  },
  "today": {
    "trend": "positive",
    "price": "+75.2k"
  },
  "members": "true"
}
```

I'd propose they are added to the item object.

Issue: the image links (not the API link above, the icon URLs) are for the the g.e on the website, and to my knowledge, only work for tradeable items. For example, `https://secure.runescape.com/m=itemdb_oldschool/1561977037620_obj_big.gif?id=1` will return a 404.

I know that this project has a folder with all the icons, however using a github link as a cdn for images isn't ideal for some. Alternatives could include: 

- Scraping the url that the wiki uses (can it change?)
- Using runelites cdn (which I think I might do myself)
- Using the icon folder in this project

**Comment by osrsbox** [comment]
This issue is very similar to the issue #119. The item ID can be used to query both of the official OSRS GE icons using the provided base URL:

```
"https://secure.runescape.com/m=itemdb_oldschool/1561977037620_obj_sprite.gif?id=" + item_id
"https://secure.runescape.com/m=itemdb_oldschool/1561977037620_obj_big.gif?id=" + item_id
```

There was an issue #108 that we were discussing to add detailed item images (from the wiki) and the last I heard, the author was trying to determine how the OSRS Wiki URL changes (if it even does). I am not sure how RuneLite CDN handles the item icons. FYI - the icons I have are extracted using a custom RuneLite plugin, and I cover every valid item, not just the tradeable items. Maybe the plugin I have uses the RuneLite data, but I have not looked into it.

Also, you do not have to use the github URL for querying the data. You can use a URL such as:

```
"https://osrsbox.com/osrsbox-db/items-icons/" + item_id
For example:
https://osrsbox.com/osrsbox-db/items-icons/21000.png
```

Don't know if that helps?

**Comment by gc** [comment]
What you've said makes sense. Thanks!
