### ISSUE TITLE
Author JSON file populated with invalid items

### ISSUE THREAD

**Issue by osrsbox** [osrsbox/osrsbox-db#130]
As discussed in #126 - there are numerous invalid items in the item database. This issue should work towards removing invalid items. The method:

1. Determine unobtainable items. Firstly, as specified on the [OSRS Wiki Unobtainable items page](https://oldschool.runescape.wiki/w/Unobtainable_items). Secondly, any other unobtainable items as discovered in development/testing/user feedback.
1. Items used in interfaces (e.g. flatpack items have an item with identical name but different image).
1. Strange, duplicate items. When these exist they can be manually added to the list of invalid items.

As a side note, the placeholder and noted item variants will not be removed as these are easily discoverable using the `placeholder` and `noted` properties that already exist in the database, and technically these are still items (placeholders is arguable here). Nevertheless, I still think these are useful to retain.

Below is a highlight of the examples one might find in the `data/invalid-items.json` file:

```
{
    "286": {
        "id": 286,
        "name": "Orange goblin mail",
        "status": "unequipable"
    },
    "421": {
        "id": 421,
        "name": "Lathas' amulet",
        "status": "unobtainable"
    },
    "2570": {
        "id": 2570,
        "name": "Ring of life",
        "status": "no_bonuses_available"
    },
    "3241": {
        "id": 3241,
        "name": "Man",
        "status": "skill_guide_icon"
    },
    "8035": {
        "id": 8035,
        "name": "Large teak bed",
        "status": "construction_icon"
    }
}
```

Each item should have an `id`, `name` and a `status`. The `status` is important here and can be used to help classify an invalid item. The only really non-descriptive `status` is `no_bonuses_available` which means the OSRS Wiki does not have a `Infobox bonuses` template for the item even though it is `equipable` - this is most usually when the item has `0` stats, or some strange item that is labelled as `equipable` in the cache... but it isn't (e.g., Goblin mail...).

**Comment by jakebellotti** [comment]
As for duplicate items, it seems as of this update: https://secure.runescape.com/m=news/last-man-standing-beta-and-splashing-restrictions?oldschool=1
There were a lot of PVP based items that have had more duplicates created. E.g.

23642 Blessed spirit shield
23644 Eternal boots
23646 Bandos tassets
23648 Dragon javelin
23649 Dragonstone bolts (e)
23650 Rune pouch

So manual entry may not be effective if different versions are always added. Need some sort of automation to determine the original item. Probably something simple that selects all items with same name and properties, and leaves the one with the lowest item ID.

As for noted and placeholder items, instead of having 3 files with the exact same data, perhaps we can have a different format for those?
E.g.
placeholder_xx.json
`
{
   redirect: "item_xx.json",
   itemType: "placeholder"
}
`
Or something similar. More efficient on space that way. 
Same for the 'null' items, which normally aren't actually null, they are just a placeholder for an item icon (when an item has multiple icons depending on quanity, e.g. coins).

As for the `equipable` property, I think what that means is that it has a version of the model that is able to be worn by any mobile entity, not just the player. So I think the Goblin Mail is actually worn on the Goblin, and that's why it says `equipable` in the cache

**Comment by Zirro** [comment]
Would you consider storing the data and icons for these items (particularly the unobtainable ones) in a collection separate from the main one, instead of completely excluding them?

While they're not suitable for the use case of listing all items accessible to players, their data might turn out to be interesting/useful in other ways.
