### ISSUE TITLE
Add Variant field for items which share names

### ISSUE THREAD

**Issue by Austin-Schmidli** [osrsbox/osrsbox-db#136]
It could be useful to have a way to differentiate between real items that have the same name. 'Real' in this context is referring to non-noted non-placeholder items. This is most commonly found with items that have cosmetic variants but the in-game name is the same. The wiki differentiates these items with a '_(variant)' suffix in the URL. Ex: https://oldschool.runescape.wiki/w/Rune_heraldic_helm_(Arrav)

I suggest adding a new string field 'variant' to each item. 

**Incomplete List of potential Variants:**
- Flatpack 
- Top/Bottom, See: https://oldschool.runescape.wiki/w/Priest_gown_(top)
- Construction Heraldic Variants (More detail below)
- Color, Several items have multiple color variants, random example: https://oldschool.runescape.wiki/w/Villager_robe or Graceful Recolors
- 'Fullness', Referring to things like the Bottomless Compost bucket that technically change into a different item when they are Full vs Partially Empty vs Empty. This one is probably not worth the effort of maintaining, since the wiki doesn't even have different pages for these variants. But I figured I would include it here for the sake of completeness. 

**Variants of Heraldic Items (Construction)**
- Arrav
- Asgarnia
- Dorgeshuun
- Dragon
- Fairy
- Guthix
- HAM
- Horse
- Jogre
- Kandarin
- Misthalin
- Money
- Saradomin
- Skull
- Varrock
- Zamorak

**Ornament Kitted Items?**
It looks like the item information currently has some Ornament Kit variants listed the name, marked as (or) or (g). It might be valuable to also capture this information in a variant field as well as the name, but I don't really know if it matters. What do you think?

As a side issue, it appears that some Ornament Kitted items are currently missing their variants in the name. I haven't done an extensive search, but the Dragon Pickaxe, the colored Dark Bows, and the god variants of Rune Scimitar do not currently have their Ornament Kit variants in their names in the item information. 

Helpful links:
https://oldschool.runescape.wiki/w/Heraldic_helmet_(Construction)
https://oldschool.runescape.wiki/w/Heraldic_kiteshield_(Construction)
https://oldschool.runescape.wiki/w/Ornament_kit

**Comment by osrsbox** [comment]
Hey @Austin-Schmidli - thanks for posting this issue. Feedback like this really helps the development of this project and helps improve the accuracy of the item data. This issue has a lot to do with #124, #125, and most importantly #126. There are a number of items that have incorrect, or partial data, or items that have properties/equipment stats from a similar item, but it is the wrong one. There are also cases (like the heraldic helms) which has the correct data for each version, but are indistinguishable from the other heraldic helms - like you said this is because of the name.

Issue #126 bought up numerous issues with the data scraping method. Since then, I have been rewriting the `item_builder` modules to extract wiki data based on item ID (something that wasn't available when starting the project). I am also working simultaneously on populating invalid items (see #130). These developments should help fix the problems you listed.

To specifically address your issue. I am going to add a new property for all items called `wiki_name`. This will use the hard work that the wiki admins have done to distinguish between items with the same name. The original `name` property will be kept, as this is raw data from the cache, but the additional `wiki_name` property will be added and populated from wiki data. Below is an example for a `Broken axe`:

```
id: 498
name: Broken axe
wiki_name: Broken axe (steel)
wiki_url: https://oldschool.runescape.wiki/w/Broken_axe_(steel)

AND

id: 500
name: Broken axe
wiki_name: Broken axe (black)
wiki_url: https://oldschool.runescape.wiki/w/Broken_axe_(black)
```

Even when the wiki doesn't have a specific page for a changeable item (which is instead handled by versioned infoboxes on a single wiki page), I will try to populate a suitable `wiki_name`. For example:

```
id: 552
name: Ghostspeak amulet
wiki_name: Ghostspeak amulet (Normal)
wiki_url: https://oldschool.runescape.wiki/w/Ghostspeak_amulet#Normal

VS

id: 4250
name: Ghostspeak amulet
wiki_name: Ghostspeak amulet (Enchanted)
wiki_url: https://oldschool.runescape.wiki/w/Ghostspeak_amulet#Enchanted
```

I think that this change will address most of the items/scenarios that you mentioned. I know the examples are not the items you mentioned, but I hope they provide an idea of what the change will be. I have rewritten the `item_builder` modules, but have only tested up to item ID 5,000 - so I can't yet check most of the items you mentioned.

The list you provided is actually really useful, as it gives me a number of items to test (beyond the small list that I have put together, and the other erroneous items listed in other issues). If you have any feedback, please feel free to post a comment/reply.

**Comment by Austin-Schmidli** [comment]
@osrsbox Wiki_name seems like a great solution to this issue!

Some additional items/item classes that may need to be considered/tested:

- Keys https://oldschool.runescape.wiki/w/List_of_keys
- Burnt Fish
- Broken Axes, You already brought these up, but I thought I'd mention that they also appear to have the wrong icons in the database. The items have been discontinued from the game, which might be contributing to this issue?
- Broken Pickaxes, Same as above.
- Coin Pouches, Uses versioned infoboxes, see https://oldschool.runescape.wiki/w/Coin_pouch#Fremennik
- Pet Variants (Pet Snakeling, Rock Golem), Uses versioned infoboxes
- Ancient Pages, https://oldschool.runescape.wiki/w/Ancient_page The wiki doesn't have individual pages for these items. I imagine you can presume that they just go in order?  (11341 - 11366)  
- Unfinished Food Items (Unfinished cocktail, bowl, crunchy, batta, potion) This one seems particularly difficult if not impossible to account for without manual work.
-Chompy Bird Hats

Something to be aware of is that it appears some items use both () and #, for example: https://oldschool.runescape.wiki/w/Old_notes_(Dragon_Slayer_II)#Ungael_2 It's not a big deal but might have some impact on how you create the wiki_name string. 

I originally wanted to create a more exhaustive list but there are a lot more duplicate named items than I had thought, and the wiki seems to handle them all with little consistency. 

For now I'm going to try and more fully understand how exactly your item_builder and the rest of this project works, and hopefully find a more meaningful way to contribute if I can.

**Comment by osrsbox** [comment]
@Austin-Schmidli - just pushed the changes to close this issue. Tried my best to manually check all of the items listed.
