### ISSUE TITLE
Npc API Cave Horror uses wrong id for Black Mask drop

### ISSUE THREAD

**Issue by Justlfied** [osrsbox/osrsbox-db#204]
The item ID for black mask the API returns is 8921 which is the normal black mask but Cave Horrors drop Black Mask (10) which uses item ID 8901

**Comment by osrsbox** [comment]
Hey @Justlfied - just got a some spare time to look into this issue, and you are right. It seems as though the item returned from an OSRS wiki SMW query for the Cave Horror (and Cave abomination) returns `Black mask` uncharged version, instead of `Black mask (10)` -- as it should be. So when I do an item lookup to get the ID (using the name `Black mask`) the wrong item ID is returned. 

What I might do, is just hard code the `Black mask` drop to be `Black mask (10)` instead. I don't like hard coding stuff like this, but seems safe in this instance. Will make the change during the next in-game update. So it should be fixed by Thursday next week (2021-02-11) approximately.

Thanks for reporting the issue. It is nice to fix stuff like this.
