### ISSUE TITLE
CRLF line endings

### ISSUE THREAD

**Issue by nwalsh1995** [osrsbox/osrsbox-db#48]
From looking through the code it seems like most of the line endings are CRLF (Windows) from what I can understand from some GitHub docs, the line endings should be stored just as LF.

https://help.github.com/articles/dealing-with-line-endings/#platform-all

Note that this conversion will have to touch a lot of files with seemingly no changes since the lnew line characters are hidden on the diff. Therefore, this conversion should be done once and without any other changes being added.

**Comment by nwalsh1995** [comment]
@osrsbox let me know if you really want to take this issue, otherwise I should be able to try the conversion before end of week.

**Comment by osrsbox** [comment]
@nwalsh1995 - this sounds like a good plan to me. I agree that LF line endings should be used throughout the entire repo. I am happy if you want to tackle this issue.

On a related topic: Most of the tools in the repo that generate output files should already have LF line endings (explicitly coded). I will open another issue to check that all output files explicitly set `newline="\n"` when opening a file - so that we don't get more files created with CRLF line endings.
