### ISSUE TITLE
setup.py packaging docs folder in the incorrect location

### ISSUE THREAD

**Issue by nwalsh1995** [osrsbox/osrsbox-db#88]
Just installed 1.0.7 and saw that the created `docs/` directory does not live under the osrsbox folder in the install.

You can reproduce by `pip install osrsbox` and then `pip uninstall osrsbox`.

```
» pip uninstall osrsbox
Uninstalling osrsbox-1.0.7:
  Would remove:
   venv/lib/python3.7/site-packages/docs/*
   venv/lib/python3.7/site-packages/osrsbox-1.0.7.dist-info/*
   venv/lib/python3.7/site-packages/osrsbox/*
```

Notice the `docs/` folder is right under `site-packages` instead of being under `osrsbox/`.

**Comment by osrsbox** [comment]
@nwalsh1995 Thanks for reporting this issue. Did it do this before the recent changes? Any ideas on how to use the manifest file to copy data to a specific target directory? I'm coming up short on a solution that automatically does it, so I don't have to create the file in the `osrsbox` directory manually.

**Comment by osrsbox** [comment]
I tested a fix where the `docs` folder is in the package directory, but it breaks the `.load()` function and the `all_items` module in the `items_api`. This is because it tries to load the parent.parent directory to find `docs/items-complete.json`. Kind of stuck, as moving the docs folder breaks the repository version, but I agree with you that the `docs` folder for the package should be moved into the package directory. Will try think of a potential solution.

**Comment by nwalsh1995** [comment]
> @nwalsh1995 Thanks for reporting this issue. Did it do this before the recent changes? Any ideas on how to use the manifest file to copy data to a specific target directory? I'm coming up short on a solution that automatically does it, so I don't have to create the file in the `osrsbox` directory manually.

I'm not sure, there were the packaging issues from 1.0.2 -> 1.0.7 so it could be anywhere in there.
