### ISSUE TITLE
Duplicate items: Members items with non-GE, F2P duplicates

### ISSUE THREAD

**Issue by osrsbox** [osrsbox/osrsbox-db#94]
There is a new issue regarding duplicate items in the database. There seems to be items that are exceptionally similar, and are very difficult to identify which is the actual item. The example below is for the Abyssal whip, but there are a collection of similar items. The snippet below seems to be the actual whip:

```
{
    "id": 4151,
    "name": "Abyssal whip",
    "members": true,
    "noteable": true,
    "tradeable": true,
    "tradeable_on_ge": true,
    "linked_id": 4152,
    "cost": 120001,
    "lowalch": 48000,
    "highalch": 72000
}
```

and this item ID seems to also be a whip, but with some different properties...

```
{
    "id": 4178,
    "name": "Abyssal whip",
    "members": false,           <= DIFFERENT
    "noteable": true,
    "tradeable": true,
    "tradeable_on_ge": false,   <= DIFFERENT
    "linked_id": null,          <= DIFFERENT
    "cost": 6,                  <= DIFFERENT
    "lowalch": 2,               <= DIFFERENT
    "highalch": 3,              <= DIFFERENT
}
```

Not quite sure how to deal with this at the moment.

**Comment by jakebellotti** [comment]
There are quite a few items like this. If I had to guess why, it might be because the item is used in a quest/cutscene/interface somewhere, and a separate item was created in case of a bug. An example is the Draynor Bank Robbery, where the Blue partyhat had a new item created for it. Not sure where that might be used for this particular item but it is an idea.

Looking at the data below, we can notice a few similarities and differences.
1.) Name & inventory model are always the same
2.) PlaceholderID and NotedID are only available on the correct version, with the others being null.

Query[Abyssal Whip] Results[3]
`CacheItemDefinition{id=4151, name='Abyssal whip', resizeX=128, resizeY=128, resizeZ=128, xan2d=280, yan2d=0, zan2d=0, price=120001, isTradeable=true, stackableInInventory=false, inventoryModel=5412, members=true, colorFind=null, colorReplace=null, textureFind=null, textureReplace=null, zoom2d=840, xOffset2d=-2, yOffset2d=56, ambient=0, contrast=0, countCo=null, countObj=null, groundOptions=[null, null, Take, null, null], inventoryOptions=[null, Wield, null, null, Drop], maleModel0=5409, maleModel1=-1, maleModel2=-1, maleOffset=0, maleHeadModel=-1, maleHeadModel2=-1, femaleModel0=5409, femaleModel1=-1, femaleModel2=-1, femaleOffset=6, femaleHeadModel=-1, femaleHeadModel2=-1, notedID=4152, linkedNoteID=-1, team=0, shiftClickDropIndex=-2, boughtId=-1, boughtTemplateId=-1, placeholderId=14032, placeholderTemplateId=-1, equipmentScreenOptions=null}`

`CacheItemDefinition{id=4178, name='Abyssal whip', resizeX=128, resizeY=128, resizeZ=128, xan2d=280, yan2d=0, zan2d=0, price=6, isTradeable=false, stackableInInventory=false, inventoryModel=5412, members=false, colorFind=null, colorReplace=null, textureFind=null, textureReplace=null, zoom2d=840, xOffset2d=-2, yOffset2d=56, ambient=0, contrast=0, countCo=null, countObj=null, groundOptions=[null, null, Take, null, null], inventoryOptions=[null, Wield, null, null, Drop], maleModel0=-1, maleModel1=-1, maleModel2=-1, maleOffset=0, maleHeadModel=-1, maleHeadModel2=-1, femaleModel0=-1, femaleModel1=-1, femaleModel2=-1, femaleOffset=0, femaleHeadModel=-1, femaleHeadModel2=-1, notedID=-1, linkedNoteID=-1, team=0, shiftClickDropIndex=-2, boughtId=-1, boughtTemplateId=-1, placeholderId=-1, placeholderTemplateId=-1, equipmentScreenOptions=null}`

`CacheItemDefinition{id=20405, name='Abyssal whip', resizeX=128, resizeY=128, resizeZ=128, xan2d=280, yan2d=0, zan2d=0, price=750, isTradeable=false, stackableInInventory=false, inventoryModel=5412, members=false, colorFind=null, colorReplace=null, textureFind=null, textureReplace=null, zoom2d=840, xOffset2d=-2, yOffset2d=56, ambient=0, contrast=0, countCo=null, countObj=null, groundOptions=[null, null, Take, null, null], inventoryOptions=[null, Wield, null, null, Drop], maleModel0=5409, maleModel1=-1, maleModel2=-1, maleOffset=0, maleHeadModel=-1, maleHeadModel2=-1, femaleModel0=5409, femaleModel1=-1, femaleModel2=-1, femaleOffset=6, femaleHeadModel=-1, femaleHeadModel2=-1, notedID=-1, linkedNoteID=-1, team=0, shiftClickDropIndex=-2, boughtId=-1, boughtTemplateId=-1, placeholderId=-1, placeholderTemplateId=-1, equipmentScreenOptions=null}`

Not sure how you prepare the batch of items to scrape in your project, but in mine I start off with all the information in the cache, filter out placeholder and noted items, filter duplicates such as these and then scrape the remaining items.

**Comment by Austin-Schmidli** [comment]
Are there any known cases where the first (lowest item ID) instance of the item isn't the "real" one?

**Comment by osrsbox** [comment]
@jakebellotti - thanks for the feedback and extra information on this issue. I prepare this project a little differently from your method - but I do like your approach and think it is valid. I really wanted this item database to have every single item, no matter the use in-game - then people can filter items based on their requirements. With that being said, I think there needs to be a new property for duplicate items to distinguish the _real_ item, or _most commonly used_ item. That way, people can filter the item database on what their needs are.

I am still thinking about how to handle this change, what the property should be called, and how to populate it (but I like the placeholder and noted ID differences - this information is now readily available in this project added in commit 0c941c67ac79a1d434e6f51543b168b6f70c9cda). This brings up the comment from @Austin-Schmidli. I am not sure of any cases where the lowest item ID is not the _real_ or _most commonly used variant_. Maybe the item ID number, in tandem with the placeholder/noted ID property is the best approach. 

For now, I will continue fixing the `items_builder` modules to have better item data, then look at adding a new property to help distinguish duplicates in the database.

**Comment by jburleigh1** [comment]
Hey Guys,

I'm fixing some issues that have arisen on my site tonight due to the latest item sync and I've found a bunch more duplicate items with the same issues as above have been added. I believe @jakebellotti is correct and that these items are used in the game as part of a quest/cutscene/interface.

Examples:

Item Name | Item ID
-- | --
Vesta's Longsword | 23615
Zuriel's staff | 23617
Morrigan's javelin | 23619
Statius's warhammer | 23620
Ghrazi rapier | 23628

and if you look up the data stored on these items, you'll see different traits to the originals, unfortunately, it's not consistent. Some are listed as members items while some are not. Some are listed as notable while some are not. 

https://www.osrsbox.com/osrsbox-db/items-json/23615.json

For the moment I'm manually removing these items from my own site so they don't interfere with the correct items, but I believe more of these duplicates are going to sneak into the data as time goes on. 








The item ID's for all the items are

**Comment by osrsbox** [comment]
After a while of thinking about this problem, and getting feedback - I have just pushed a commit and updated the PyPi package to have an additional property named `duplicate`. This property aims to help identify duplicate items by comparing all the items in the database. This is achieved using a _"first come, first served"_ principle. The lowest item (based on item ID) is considered the _"original"_ when multiple items with the same properties are found. The properties that are used for comparison are listed below:

- `wiki_name`
- `noted`
- `placeholder`
- `equipable`
- `equipable_by_player`
- `equipable_weapon`

When processing an item, if an already processed item has the exact same values for these properties... the item is marked as a `duplicate` - where the property value is set to `true`. This should make it easy to find duplicates... as illustrated in the following code snippet:

```
from osrsbox import items_api

all_db_items = items_api.load()

for item in all_db_items:
    if item.name == "Abyssal whip" and item.equipable_by_player and not item.duplicate:
        print(item)
```

The result of this code finds only one instance of the _Abyssal whip_ item which is equipable and is deemed to not be a duplicate. If the `not item.duplicate` test is removed, a total of 3 _Abyssal whip_ instances are found that are all equipable!

I think this solution provides a harmonious balance of:

1. Retaining all items in the database (i.e., not removing the duplicates as they might be useful)
1. Enabling developers to easily filter duplicates

If anyone has feedback regarding this change, or any errors... please post a comment or feel free to open a new issue. I have done some testing, but the large number of items makes it hard to test everything!

**Comment by jburleigh1** [comment]
very happy to see such an elegant solution for this one! This has worked almost perfectly for me, with very minimal code on my end. Thanks a lot, you're a star.
